apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: LoadBalancer
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1
status:
  loadBalancer: {}
